### ISSUE TITLE
Tidy up Python Code Styling - fem-gui

### ISSUE THREAD

**Issue by timcnicholls** [stfc-aeg/lpd-detector#2]
_From @MRichards99 on October 4, 2018 7:42_

Most of the code in the lpd-fem repo uses camelCase, but a lot of Jack's work uses underscores (as per PEP8). It would be nice to refactor the code to use all underscores. This isn't high priority (nor is it particularly interesting) but could be good to do if there's time. 

_Copied from original issue: stfc-aeg/lpd-detector-forked#2_

**Comment by timcnicholls** [comment]
_From @MRichards99 on November 5, 2018 9:28_

Some refactoring of variable names has taken place, however commenting code is now being done as I work with different sections of the code (as opposed to a few days _just_ commenting.

**Comment by MRichards99** [comment]
I feel the styling has improved quite a lot, hence this issue is being closed.
